sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
before_script:
- npm prune
script:
- npm run build
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:ci; fi
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  browserstack:
    username:
      secure: CfGuW749/E+p5Gdy6tmPM+l8pXAacMHSMby0BHd6bOWjB88tjoR1jNUkC1g06bzp1wfNqPsBbmJmdtiMrAi/isGspXce7UVKx8fJkyhnS7KFMMNx7kYtaB33YlFRA2YzNLnm08F6kRetWR71iuhawCGJwa2CPy/8hEWACo7HdLL3JVgkUzhbWATGKKLSGImoiR/rifRv3kVr9Mrj5WM288aLBbCryjAsaf1xydp1M6PVX4Sb31IV+ei68x5EmXMyZpzEOLGes5JUB6fDhjfoHXtWkAsoIE+NIX/soLpyUOYb9su0tdaGfhSrleKI62aZXfv1uNo/P9LvIu544MoRx/gCfaCRvmENSobqxUx1gtqco50bItQP8FB9qKsqGtfHCH7uA9qlFuSQa9zwPm3XDUyPr685IskyZSGzDtf3NwcImX1aK7wUT5h8VFf4CjwYCRKPKML9Kb3Ow9mIDpNq6uWR2pjOwwP8Kahd5Dq5AE/dETrd6HwzWEjy5TwYbC3OgDM8gkaZq5mzjcYNa0YQKd7Q/4iJ2qDqPibrzQz8XKf5JYOR/XdKPoDJLt66SdSovYqJVIM9205A1L7sPZFqZbQBg+prHBRB1o5wjZzfCIp9FPJexlqUg9kgpsaBG5OL1ol1SFhJZJ+XdQmGOSBFhIRjVk1zmGn6Ao8ykoi99mc=
    access_key:
      secure: aedy7eocHCz9EfUUPomiUSCjbbQdgXj+dqsC2Ftq85cYeKM8XI+GD8FXBhtK8ohXjW7End+cpV48H9PmTNMOZS9C1FF4l5cJRvhDytSUbub8w3usk5KhgsNrdmgFW3YA7wdOpeeOexz8PS1vsvKLYIK3356A69sWuIHA3Avy7Soa4zz9hi6TJhtlgud5spLI4qAfLoJHpim25TJ4JePAN2mpDRwdJi+6Gd5W0fln2bCKcSu0f513ucZAyvY9yuPAMKbwzZovunCE3fRhamwI9c0zpFwhTnZyD1CA8A6ktDkUB6l84VvxAc18BLNHVht2Pekq1xhJr2+xjSHYQapnnF4bN4DI9BxwKFWDtCuTYzsMqx9frkvdiLYHuwskrbpqntKcP+gg+ElzTisyCoYJWVlrrUnBG78Zx5rQIPC/kRKuw+FCZQJozZky1X2kM6tsBdLo/EX0IGC7HRHxLkEJCvQyo9TQQ5AvnUIawyjvxmXzMur4O2N/jVPPKmCxbeiMW/f9yXrwMxlmEmdUlu+H+BDll/pteiZhAb4rFqk23UAcp1SYjQAIVDz+XBapHnfe5lLsxzN5kNCwLBXHc13kvmtRV/+pmM0sPmyZmgn9kG99vbRgbFi4yxYry/odgEPI0fpgK8etLja14FhANCbVekUIfRIii0fBw+3mr/JmGC0=
env:
  global:
    secure: TRAt03HWQBXbuIaqTZIrtB17ZxqdkY9iOirn84NMKUNpCcvdY/Hj099BCMpFHcvu4dFDKp++sGTNQ9uVQqXvr1fCVtpkqAlcHFHHm9EyUq/5y+oY+1jwEFsf7LhhWtK/64da3Y4EYh9rE9iYw0h4G/+IurLNtssCHmKeMNb3fcorTBZTFhG0fhpRLq7+MH2qnudmSqnLvTMrVG6vZrv7Ozono54xC+unNLGP2nqdlb4JH0yFmwc69F/vp79ZzG83rpXNOCoEeqapQKMFmgF8DrDM6rbo8dtTHrj57nTPhzC3qCfNfg+o9jQwM8da/X3ivcOLyO3FNeLeVKMrfvSzfzW/kxjo36BhF0x8IKjWKCNatRVYzLKVyR/yK4SiMAcWcSjdBgEd6VrT3B04dg0xGj6IVsbj0kqRSM7DEikQAq/8n2GYNtQzlHNIlQgFgtlc9MG8cghKGd+OSrPTjbbcfb/2ibBXrMyfjHyj9al3RIWYOTHTtsixfailJ473NiU2JC2+I9mzy00YeBZ48FnjqvxyD1DFjbl/TO8oTtJQnoA5+py7u0GpIgPQGLIPAYeUU0dTbSeKWWTb1kHOe/wtr/DmR7iPSQQns8HTZObE1H4yXGKVQFIx8Gj8ka7ilMw3uKl7A+vcD/dE3rqc8ivnt9oQSjKagVUGATKImMEA+5o=
    secure: srDavyH1Fg5DNLMuB7Z7WVxMbvpAU9MIZF6g+x2nPa5Mra8j0Xtes1OtG2DhT3YwkWmJupnLGlIfVqhuJwWKcNTKkNEhCNeh3EmtQgP1JEeKZm0Mwy78ReTxN/bR11OJn6lsQBkEzX4aOCr2yKYyImo7mvOk8P6fdXuVvoKEV+0CCgHV3eaAmTiPEes652DV9fZvXxVju0AvPd8ImxSM8itIUqLPysVseK2KLiGsnadFiNB2doDj2pwhUvfeoqxgwMaLSYoIFVv3MsUg8Z5HteW5h5Avf41J4KD1p+0yJH5MweJ/b7w6a2zbMU5juV7vjwUIvkMb7KhmrHEKhzbLku3BrYH4i7hqLZJvFdjkZahvfn4vIEh/8YW5RtMtmHk0DkmAnGQpgUWOO25qg/JwD4cI2NeMboSJcjknDY3Y0AmTq6Ouzv0+llze1YEFGETG81a5mzwEd3LuknJ7xYqsdSe1Un9OD+Yug7fQq91EhPo2flfw4Ro9Rm/F8IMo3Hmj++hJZZTsqg0PPqLcv2pRsvKcKlGtGjbYYMU6M499tFSxkC5M24BdTH5GhH3D+30c7b75jUmieQ1CjnjetAej9R5Tbze9Np5yrKlsGYuOi4rVORKXLpSC4Rb4ZEjZ6Wm1GuzTQCYF6z6x4tUkaCdtyK3eh0yj7YsevmvGITMOdXY=