sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
before_script:
- npm prune
script:
- npm run build
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:ci; fi
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  browserstack:
    username:
      secure: CfGuW749/E+p5Gdy6tmPM+l8pXAacMHSMby0BHd6bOWjB88tjoR1jNUkC1g06bzp1wfNqPsBbmJmdtiMrAi/isGspXce7UVKx8fJkyhnS7KFMMNx7kYtaB33YlFRA2YzNLnm08F6kRetWR71iuhawCGJwa2CPy/8hEWACo7HdLL3JVgkUzhbWATGKKLSGImoiR/rifRv3kVr9Mrj5WM288aLBbCryjAsaf1xydp1M6PVX4Sb31IV+ei68x5EmXMyZpzEOLGes5JUB6fDhjfoHXtWkAsoIE+NIX/soLpyUOYb9su0tdaGfhSrleKI62aZXfv1uNo/P9LvIu544MoRx/gCfaCRvmENSobqxUx1gtqco50bItQP8FB9qKsqGtfHCH7uA9qlFuSQa9zwPm3XDUyPr685IskyZSGzDtf3NwcImX1aK7wUT5h8VFf4CjwYCRKPKML9Kb3Ow9mIDpNq6uWR2pjOwwP8Kahd5Dq5AE/dETrd6HwzWEjy5TwYbC3OgDM8gkaZq5mzjcYNa0YQKd7Q/4iJ2qDqPibrzQz8XKf5JYOR/XdKPoDJLt66SdSovYqJVIM9205A1L7sPZFqZbQBg+prHBRB1o5wjZzfCIp9FPJexlqUg9kgpsaBG5OL1ol1SFhJZJ+XdQmGOSBFhIRjVk1zmGn6Ao8ykoi99mc=
    access_key:
      secure: aedy7eocHCz9EfUUPomiUSCjbbQdgXj+dqsC2Ftq85cYeKM8XI+GD8FXBhtK8ohXjW7End+cpV48H9PmTNMOZS9C1FF4l5cJRvhDytSUbub8w3usk5KhgsNrdmgFW3YA7wdOpeeOexz8PS1vsvKLYIK3356A69sWuIHA3Avy7Soa4zz9hi6TJhtlgud5spLI4qAfLoJHpim25TJ4JePAN2mpDRwdJi+6Gd5W0fln2bCKcSu0f513ucZAyvY9yuPAMKbwzZovunCE3fRhamwI9c0zpFwhTnZyD1CA8A6ktDkUB6l84VvxAc18BLNHVht2Pekq1xhJr2+xjSHYQapnnF4bN4DI9BxwKFWDtCuTYzsMqx9frkvdiLYHuwskrbpqntKcP+gg+ElzTisyCoYJWVlrrUnBG78Zx5rQIPC/kRKuw+FCZQJozZky1X2kM6tsBdLo/EX0IGC7HRHxLkEJCvQyo9TQQ5AvnUIawyjvxmXzMur4O2N/jVPPKmCxbeiMW/f9yXrwMxlmEmdUlu+H+BDll/pteiZhAb4rFqk23UAcp1SYjQAIVDz+XBapHnfe5lLsxzN5kNCwLBXHc13kvmtRV/+pmM0sPmyZmgn9kG99vbRgbFi4yxYry/odgEPI0fpgK8etLja14FhANCbVekUIfRIii0fBw+3mr/JmGC0=
env:
  global:
    secure: UDlk6lnxVSX30IQZKHnEgepWiFBJnL/ocgx4heKNJAZdekPKmD54sCFmdRZpy4MyUFcB+XKe5mrBg1RtNfkoJyzsBxk5No/eLISnAsmBYxsNC9QsndvIEcUqrFXf0NK3XArWzPw6nQD1ba8g0a1yaR8e4hM0AHhxl14PtoG3vj+cPZHMBiQ2fXjr7iHXFd4BSISJ1OECtEj/uKhwmoBLek/khpNoBwXZItUALUYmXbOezeV+d4efoO1soi78Q+T5PetV/cdMinjMR+eH5UFyZgy2kA6Z/Of1SEflWJJ1kYgRuseG3u8nBf8xcIaJ0J+jMXk1y7lagRZqA1KJ2FZNvJMO2xddIs8jOiovGWZ1L4+FoySBCYwwU9pLkiGHWOj0cLe74zo6jiIFxOTjJAQbGMbSbERGw78gPPXYLT2rkXvEbb9M85XsFHNRHwGwyyoucjsuMs4Ric7Tly5MlbQ+5BEcuDP8mqwEEVW1XtBWE0x69t4YvKRo/fMQQRafMKtU/Y8INd2acNXu9F9sz4+A/hsYErm6NvEQqk7FaAEIoiepcvZeBxhVCGh6WUsg4rWInUpkNMh/YBSG7TaiHGpQKjmIZ7B7VqIleJx+PSmQXECE/qv6FaDo5AHvGJKTw21u66iABggGpTB0oxkB2lHvghJpgtIB1d3L5YuI9lbbsKY=
    secure: skWBvPlCiJhw2XXLk8LosWbmCSXAvvSLw6CBzHSLtrE6HcsgnSRkdf8Q8uT8A4GF8Eq3jW1uL7kCOF/n3feP6JVonLh1J50KOx4pGxbf30AN3p7ku5XJLzKTd+qiz88ve/8loiRqdlGHlSznVJ0mlviVFy34Inb+mLz861qTBUiOkk+yDL3cIDgSQLomEdFGE/CDpIpsi4jXagDSO63tMCIGYhYudD6XpP9U5SMZqrdoTFjsgqOsH7d271GZPt6FFG1xGjQWWAAvoBjzRZUK4EEyhegxQZARhH58lsxXJMajqAuCxQkj4VUerTeAYpBgCevIpUpe+MLIAciWqbQCrYZObrVsElQmHSkqL4OX6HRVHxn672RHCQivrkWKlVGaRm3sK/o4F/sPU4H8BeGThA7B+d3SkWhHsQMnuaQY+dHRfq5aYIeWX9E10xfYpnOfbYaJPxRLubZobesnLz2C7eqOiAF5csTKoWJYDf5qjv+G6gY/FrZUREO35l1yvyvlqEakmoBQPN8LdcDFH3dvfJcNS67OVOvzWNPrqcnZm0jMWCQtt9T2Z/5R3SHBr+4F6H5Ec5DoHg9412nZTL/jEmQhIZrS1bj7QZS/rWKW0wEcyWslp393zDssIYL80SebDmD76GruoXTLX7wAAUwh6fHFhQ89kuhzwT7htPkEomI=
