sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
- npm prune
script:
- npm run build
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:ci; fi
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  browserstack:
    username:
      secure: oifYNaUwrECaBJDQZXwWOzWXd36lkfm655au+Q8WxnEktJ9UHNqDX8xw0Vrtq6TZOX5tckiN9GdR5yQbilhsj9cF7DbB2oWytNNFizSy5jRmgoHG3v4JTaTd50Z/v13s6+VyOZAeE1m47MlfzQnSSfydzIZUiC8cjBR1UPWIvR8mAyRZADM365T9u8uo28TqtDAWtKXR/hr++c6EHjvw/fxuVdoO6DKNJbdJr1TjjMFtJchmwi/C3bmw+UhKmqEh7145yVsoKhGH6eq5TRn45GvWX8xHQUzYa5v/cjqxKLkJ79+Zx5A5GgbAPckuYq3S0U1wSFdOQTami8ns1R0pEloDOiLMF9/Jr+IFrXBm/e3E0rWHvGRmLIG1NtSNzuIxGHUVYgkMuRKWij8FlV7obUgqWa0+pbu/KbymtDx2wupIpKA33bHCOVfSn406OcCF4Yh0NLeaa7tfQbiNfq34Fi7gxz828VJwuagqDcP0BU9gUot4dnTaYEbnuThVlE1UZw4+ocd7rIl8sXUSK2WZF1Rwns65MoX8K6NRoSSCbZ6wDkivKlwvTFoeBtS2/T0MYdLe2hcFYLmXymOX38gaJa4yneW4HkCyNhHdS6OfNuRaomPxn0fED7sjMSzioNLfl9J8V0j+lveMNqV5G1Z+nvQ73j2Y3+XRUTiGU/warHA=
    access_key:
      secure: HK8ioc7OlecgR3+CgU2fokJmxmsO9FnQKPlTpVo5msyzpLe23f/s91CD8zjQuYUh7MPvobb7muKtGAtzRhvlGC2bfcS5h+Q9YCAlzwYyoqsgI9xICFq29AUgOKj4d07f8ifdte26r+bvhFvoz2Gjbl1yePgkgBVtZXO4cyC70/GPhZz6W6fDjwM3dgQE8AjmfuhpujhX+YGA/5Nf6bx33bK40JFWbYRqA9mIoVAMZZ+v/3pGeJpZJwhPrKY/SPq5UJBNjCReKXxuskvNWcGOs/CQ6VsxUxdViy1SqsrR9ezILH9BcgwBDKGzkhAMCFygVOMiC/O3arzX1kSFGH/GFcslSg/pkT21z98120Ux3LCiZslOJntTpDpBmExaPz7gDUj+VRfBv8eHrRmaM1713EW6qvc7wQFR3gYD9f2wWwPEneX2rHfzUhmBN26bGlryQK+ZbAiW3n7EUY1lFPF9D1UdTJ38WP5xwBU/1fOolVPBg134hkTzA90racPRhQNOW4KFVhLGpbK5VxiCGloKF+6yM2hAAkp4OZyMzK+v+Fjecpg3+lEqXn1HKcKz8uNcYYdGgDqW1A54C/MAEGJ7oLvRVQuQHFjpcjz3FtR3zic2P0Pe5u7f4PlE5aHy9YkC3Pmdh4obDkaznUKmxMPgdSPnEzykGXsBvc/lHUFDi1E=
env:
  global:
    - secure: gZkLEExtLiDXbkZ6a2kKl6BdFYzTztpnF/TMse0dVPZgC46dOZ3i0KClGo6Q5OhAVu2+97qbW8ye9iWmShF23nyJUqItqfi5wqn5ytzEoN10eEE/jcxn2BwBtpAB4VuiIh2RtPjWK4q4ji7r18O8jub3H64pofTr6tX1b069a/N4huw9xebGjcAcb8CP9hv184QDKEVT/ksr8F9f1/3n2uB7dofeERZTw6fmxTsHcGJ9y1irI/A9xp4HVXOshQWE6A/h5kJHuRdjyd6y/yNts2hC6vpbcWDr1eWKwYUALkQoYciB7RZaJOHKLMKWeDqfMEm5gx92Q1hLENfu4HQBWZglR7qhpZVWhk6Tfaj3p2OfM1IolQNG8mhk7GUslqsGo5YX6gQttls4OieXFPft0qMZnFReTcasXgIlBmhYQn7CqgxTtSqhP8vmIB90zHwb8Ou8FnsF1oae5vl93+UuhUjJsT62Zlw5f8VmUQODu7wkQYtb39tfzgX7KKtuTI5D+RmI73CpZaTrQMeQVl22Dpp0N1+7MKBxj4unCpi3J1xPoNWfXlgP+uld9L6bYUgfxXustPTSfZ6RuJpI4wahzBY6SksLwBtGLo47xrKi3W22BhP0oi+jPQmqacOH627HD62mD8PFfLB00TlqwtLP/vjAgPGOR8af7vYVzkN0lRA=
    - secure: aTXWe620VGyqmvC9uaziATyyBOzeMbzp75w9pYU95kBb1IlHo6H0+04OveLu4eGRVS8kNTKgoMq727im53NGExfAMnSAQrhOmZuNWpUo3cEtTmwT70pfL9MDT6OMhIqvugf2bijGfxH/pUYF1fdjGbmXT05QpqbTJrrE2jY903DQ6CJINzAb2M2jaC2/xYMK1wNE2I+/ROWp2oiDx+7EVkap228zy2axiZpJJ5FpE1khps3zahjRgjTlv5MnltYSTDpB8XZpVEp1dh61J0IuN7by1VJ3BLdbU9UClD3pcZ4FgCGGtmAGsLveepuiNblujDvMeyK4WQvoPHF/robF75kzbjMimiLXpyNaWKGWv7t0JsqjHClMPuk06GGmBzfpkxGbYSfj8hmhiD6rGxrcFZ13kNrNWkgZLqiG1eX9TZf1p0XOD8OOM+NITlo1PqGxWnAOQFhmXtfUuEsjGVoaA0ZSymZuabV6nQAEbUF2JwJ8ch01OASTqewAPLterGm1n5MM18kecEhs77u/vYL8URBcptbvpC4S4Zo+BJkjMfsxc5aw8g7AZws/+x9hvhqgbtDtsf/331R0e/vM0o07Tvb7ogFWyj+1eBa6FbjMgqDERGCliBlxPUg+B3lHt14xIuAUnn4ow9AdtZ44/MFMxFC9nDxg0SmC42COzPxU3EQ=
